import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway} from "next/font/google";
import "./globals.css";

const raleway = Raleway ({subsets: ["latin"]})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.className} antialiased`}
      >
        <a href= "./">Home</a>
        <a href= "/demo1">Demo1</a>
        <a href= "/demo2">Demo2</a>
        
        <hr></hr>
        {children}
      </body>
    </html>
  );
}
